### ISSUE TITLE
NVIDIA Jetson TK1

### ISSUE THREAD

**Issue by dennyalbert** [tevora-threat/Scout#1]
Does your software also work with the NVIDIA Jetson TK1?

**Comment by trumankain** [comment]
The main issues that you will run into getting Scout working on TK1 will be dependency related due to Jetpack no longer supporting TK1, but technically it should be possible since you can utilize OTG/device mode.

A wiki with detailed setup instructions for Jetson Nano and Xavier will be posted shortly, but I won't be able to confirm re the TK1 any time soon. Closing this issue for now, however will follow up here if or when I'm able to attempt building Scout on TK1.

Here's a link on getting OTG device mode working with the TK1: https://devtalk.nvidia.com/default/topic/994397/jetson-tk1/how-to-verify-usb-2-0-device-mode-workable-on-jetson-tk1-/post/5086989/#5086989
